name: providerlib

on:
  push:
    branches: [ matern ]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.5.0'
