trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'
  
steps:  
  - task: UseGitVersion@5
    displayName: Determine Version Number
    inputs:
      versionSpec: '5.x'
  - task: Bash@3
    displayName: 'Set version number in package.json'
    inputs:
      targetType: 'inline'
      script: sed -i "s/0.0.1/$GITVERSIONNUMBER/g" package.json
    env:
      GITVERSIONNUMBER: $(GitVersion.SemVer)
